pull_request_templates:
  - name: Dev Template
    path: .github/PULL_REQUEST_TEMPLATE/dev_pr.md
    branches:
      - dev

  - name: Main Template
    path: .github/PULL_REQUEST_TEMPLATE/main_pr.md
    branches:
      - main
