server:
  port: 8080

spring:
  application:
    name: cwnubnb

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/cwnubnb_db
    username: cwnubnb
    password: cwnubnb1!@#

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      encoding: UTF-8

  # timezone ???
  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace